/**
 * SCR-011 to SCR-017 content (FR-007). Each page is transcribed verbatim from its own
 * snapshot, docs/03-design/paper-snapshot/{desktop,mobile}/products-<slug>.jsx, in
 * DOM order. Keys are the PRODUCT_ROUTES ids in src/lib/site-routes.ts.
 */

import {
  type DetailFamily,
  type DetailPageContent,
  faqSection,
  hrefForRouteId,
} from "../detail-page";
import { PRODUCT_ROUTES } from "../site-routes";

const EYEBROW = "Product";

function productHref(id: string): string {
  return hrefForRouteId(PRODUCT_ROUTES, id);
}

/** SCR-011, products-gate-entry.jsx. */
const GATE_ENTRY: DetailPageContent = {
  eyebrow: EYEBROW,
  title: "Gate Entry Application",
  breadcrumbLabel: "Gate Entry Application",
  intro:
    "Gate entry tracks the movement of materials and vehicles into and out of your premises — the step where inventory accuracy is won or lost.",
  sections: [
    {
      id: "problem",
      tone: "bg",
      heading: { eyebrow: "Problem", title: "The problem" },
      blocks: [
        {
          kind: "lead",
          size: "lg",
          measure: "1080",
          text: "At most Indian plants the gate runs on a register, the weighbridge prints a slip, and stores post the goods receipt hours later from a different piece of paper. By the time a discrepancy surfaces, the truck has left.",
        },
        {
          kind: "paragraph",
          text: "Gate Entry closes that loop. The gate document becomes the spine of the transaction, and weight is reconciled against the goods receipt before an exit pass exists.",
        },
      ],
    },
    {
      id: "inbound",
      tone: "sunk",
      heading: { eyebrow: "Inbound", title: "Inbound — material arriving from your supplier" },
      blocks: [
        {
          kind: "stepGrid",
          intro: {
            before: "A ",
            emphasis: "loaded",
            after: " truck arrives with material you have procured, and leaves empty.",
          },
          steps: [
            { title: "Loaded truck reaches gate", detail: "Material procured from your supplier" },
            {
              title: "Gate entry document",
              detail: "Generated by security, truck details captured",
            },
            { title: "SAP gate entry", detail: "Document created in SAP" },
            { title: "QR code generated", detail: "Issued against the gate entry document" },
            { title: "QR code handed to driver", detail: "The document travels with the vehicle" },
            { title: "Weighbridge — gross", detail: "Loaded truck weighed" },
            { title: "QR scanned", detail: "Gross weight updated, no manual key-in" },
            { title: "Unload and GRN", detail: "Goods receipt posted, updated into SAP" },
            { title: "Weighbridge — tare", detail: "Empty truck weighed" },
            {
              title: "QR scanned, truck exits",
              detail: "Tare and net updated, exit pass released",
            },
          ],
        },
        {
          kind: "caption",
          text: "Inbound cycle. The exit pass is not released until gross minus tare reconciles against the goods receipt — which removes the entire category of weight dispute.",
        },
      ],
    },
    {
      id: "outbound",
      tone: "bg",
      heading: { eyebrow: "Outbound", title: "Outbound — goods leaving for your customer" },
      blocks: [
        {
          kind: "stepGrid",
          intro: {
            before: "An ",
            emphasis: "empty",
            after: " truck arrives to collect goods you are selling, and leaves loaded.",
          },
          steps: [
            { title: "Empty truck reaches gate", detail: "Arriving to collect your goods" },
            {
              title: "Gate entry document",
              detail: "Generated by security, truck details captured",
            },
            { title: "SAP gate entry", detail: "Document created in SAP" },
            { title: "QR code generated", detail: "Issued against the gate entry document" },
            {
              title: "QR code handed to driver",
              detail: "Gate entry pass issued to the transporter",
            },
            { title: "Weighbridge — tare", detail: "Empty truck weighed" },
            { title: "QR scanned", detail: "Truck details captured" },
            {
              title: "Goods loaded",
              detail: "Shipping document generated in SAP with actual quantity and weight",
            },
            { title: "Weighbridge — loaded", detail: "Gross weight captured" },
            { title: "QR scanned and matched", detail: "Delivery documents matched, truck exits" },
          ],
        },
        {
          kind: "caption",
          text: "Outbound cycle, drawn to mirror the inbound flow so the pair reads as one family. Both diagrams share the same component.",
        },
      ],
    },
    {
      id: "capability",
      tone: "inverse",
      heading: { eyebrow: "Capability", title: "What it does" },
      blocks: [
        {
          kind: "cards",
          titleSize: "lg",
          rows: [
            [
              {
                title: "QR-driven document flow",
                body: "One document follows the vehicle through every station. No re-keying between gate, weighbridge and stores.",
              },
              {
                title: "Weighbridge integration",
                body: "Weights read from the bridge, not typed. Removes both error and the opportunity for manipulation.",
              },
              {
                title: "Security desk interface",
                body: "Built for a guard on a shared terminal at night, not for a finance user with two screens.",
              },
            ],
            [
              {
                title: "PO and GRN validation",
                body: "Live against SAP. A vehicle against a closed or wrong purchase order is caught at the barrier.",
              },
              {
                title: "Exit pass control",
                body: "No pass until the weights reconcile with the receipt or the shipping document.",
              },
              {
                title: "Complete audit trail",
                body: "Every scan timestamped and attributable. Weight disputes become a query, not an argument.",
              },
            ],
          ],
        },
      ],
    },
    faqSection("sunk", "Questions", [
      [
        "Does it work with our existing weighbridge?",
        "In most cases yes. Weighbridge indicators expose weight over serial or network output, which we read through an edge component. We confirm the make and model during scoping.",
      ],
      [
        "What happens if the network drops at the gate?",
        "The gate keeps working. Transactions queue locally and sync when connectivity returns, with the queue visible so nobody is guessing. A gate that stops when the network stops is not deployable at a plant.",
      ],
      [
        "Does it work on Public and Private Edition?",
        "Yes, both. The SAP-side integration differs between editions and that is handled in the deployment.",
      ],
      [
        "Can we run it at more than one gate or plant?",
        "Yes. Multi-gate and multi-plant with plant-level configuration and consolidated reporting.",
      ],
    ]),
  ],
};

/** SCR-012, products-exim.jsx. The breadcrumb label differs from the H1 as captured. */
const EXIM: DetailPageContent = {
  eyebrow: EYEBROW,
  title: "Export and Import Management",
  breadcrumbLabel: "EXIM — export and import management",
  intro:
    "A complete suite for managing every aspect of export and import, integrated with your SAP environment.",
  sections: [
    {
      id: "overview",
      tone: "bg",
      heading: { eyebrow: "Overview", title: "What it does" },
      blocks: [
        {
          kind: "lead",
          size: "lg",
          measure: "1080",
          text: "TAMS designs your EXIM solution to meet the needs of a business engaged in global trade. It integrates with your existing SAP environment, giving you one platform for complex trade operations instead of a spreadsheet, a licence folder and a customs broker's email thread.",
        },
      ],
    },
    {
      id: "compliance-gate",
      tone: "inverse",
      heading: { eyebrow: "What sets it apart", title: "The compliance gate" },
      blocks: [
        {
          kind: "lead",
          size: "lg",
          measure: "1080",
          text: "This is what distinguishes it from a tracking tool. The application owns your DGFT licences and letters of credit, and enforces a pre-delivery compliance check. Where a shipment fails, it sets delivery and billing blocks on SAP directly — so a non-compliant consignment cannot quietly leave.",
        },
      ],
    },
    {
      id: "import",
      tone: "bg",
      heading: { eyebrow: "Architecture", title: "Import" },
      blocks: [
        {
          kind: "architecture",
          columns: [
            { label: "SAP", items: ["Purchase order", "Sales order"] },
            {
              label: "TAMS EXIM",
              emphasis: true,
              items: [
                "Vendor document set",
                "Clearing instruction",
                "Into bond BoE",
                "Transfer bond BoE",
                "LC / DA / DP advance payment",
                "Home consumption BoE",
                "Ex bond BoE",
                "Bank guarantee",
                "Acceptance / vendor payment",
                "Benefit scheme (Advance / EPCG / MEIS)",
                "Bond",
              ],
            },
            { label: "External agencies", items: ["Vendor", "CHA", "Customs", "Bank", "DGFT"] },
          ],
          connectors: ["solid", "dashed"],
        },
        {
          kind: "caption",
          text: "Import architecture. SAP documents on the left, the EXIM application in the middle, external agencies on the right. Solid arrows are system integration; dashed arrows are agency exchange.",
        },
      ],
    },
    {
      id: "export",
      tone: "sunk",
      heading: { eyebrow: "Architecture", title: "Export" },
      blocks: [
        {
          kind: "architecture",
          columns: [
            { label: "SAP", items: ["Sales order", "Delivery / proforma invoice", "Billing"] },
            {
              label: "TAMS EXIM",
              emphasis: true,
              items: [
                "Letter of credit",
                "Order confirmation",
                "Benefit scheme",
                "Pre-shipment document",
                "Export obligation (Advance / EPCG)",
                "Duty drawback (AIR / MEIS)",
                "Post-shipment document",
                "Container tracking",
              ],
            },
            {
              label: "External agencies",
              items: ["Advising bank", "Customer", "Customs", "Negotiating bank"],
            },
          ],
          connectors: ["solid", "dashed"],
        },
        {
          kind: "caption",
          text: "Export architecture. The compliance gate sits between the pre-shipment document and dispatch — a failed check sets delivery and billing blocks on SAP.",
        },
      ],
    },
    {
      id: "outcomes",
      tone: "bg",
      heading: { eyebrow: "Outcomes", title: "Benefits" },
      blocks: [
        {
          kind: "cards",
          titleSize: "lg",
          rows: [
            [
              {
                title: "Improved compliance",
                body: "Checks enforced by the system rather than remembered by a person.",
              },
              {
                title: "Operational efficiency",
                body: "One data entry, reused across every trade document.",
              },
              {
                title: "Cost savings",
                body: "Fewer demurrage and detention events, better licence utilisation.",
              },
            ],
            [
              {
                title: "Enhanced decision-making",
                body: "Landed cost and licence position visible while decisions are still open.",
              },
              {
                title: "Scalability",
                body: "New destinations and licence types added as configuration, not as a project.",
              },
            ],
          ],
        },
        {
          kind: "paragraph",
          text: "Empower your organization with the tools to manage export-import activities efficiently, ensuring compliance and driving operational success.",
        },
      ],
    },
    faqSection("sunk", "Questions", [
      [
        "Does it connect to ICEGATE and DGFT systems?",
        "Integration scope is confirmed per deployment, since it depends on your customs broker arrangement and which filings you handle in-house. Licence and LC management, the compliance gate and the SAP blocks are core product.",
      ],
      [
        "Do we still need a customs broker?",
        "Almost certainly yes. EXIM manages your side. It does not replace the broker; it means the broker gets correct documents the first time.",
      ],
      [
        "Can it handle SEZ and EOU operations?",
        "These have specific documentation and reporting requirements that we scope individually.",
      ],
    ]),
  ],
};

/** SCR-013, products-digisign.jsx. */
const DIGISIGN: DetailPageContent = {
  eyebrow: EYEBROW,
  title: "TAMS DigiSign",
  breadcrumbLabel: "TAMS DigiSign",
  intro:
    "Digital signing of organisation documents inside SAP, using DSCs issued by government-approved certifying authorities.",
  sections: [
    {
      id: "overview",
      tone: "bg",
      heading: { eyebrow: "Overview", title: "Overview" },
      blocks: [
        {
          kind: "lead",
          size: "lg",
          measure: "1080",
          text: "TAMS DigiSign is a digital signature solution for SAP using Digital Signature Certificates obtained from government-approved CAs, for both organisation and individual certificates.",
        },
        {
          kind: "rail",
          steps: [
            { title: "Document created in SAP" },
            { title: "DSC applied" },
            { title: "Signed PDF stored in SAP" },
            { title: "Issued to recipient" },
          ],
        },
        {
          kind: "caption",
          text: "The document never leaves SAP. That is the whole argument — the usual alternative exports documents to a desktop, signs them in a separate tool and uploads them back, which breaks the audit chain and does not scale.",
        },
      ],
    },
    {
      id: "capability",
      tone: "sunk",
      heading: { eyebrow: "Capability", title: "Features" },
      blocks: [
        {
          kind: "checklist",
          items: [
            "Digitally sign a set of PDF documents in a few clicks",
            "Signing can be automated as part of a document output process",
            "Mass signing of PDF documents avoids human error and removes repetitive effort",
            "Signing with either an individual or an organisation digital signature",
            "No need to save or extract data outside SAP ERP",
          ],
        },
      ],
    },
    {
      id: "applications",
      tone: "inverse",
      heading: { eyebrow: "Applications", title: "Where it gets used" },
      blocks: [
        {
          kind: "cards",
          titleSize: "lg",
          rows: [
            [
              {
                title: "Invoices",
                body: "Signed at output, in volume, without a person opening each one.",
              },
              {
                title: "Delivery challans and gate passes",
                body: "Signed as they are generated, at the pace dispatch actually runs.",
              },
              {
                title: "Purchase orders",
                body: "Organisation signature applied on release.",
              },
            ],
            [
              {
                title: "Quality certificates",
                body: "Mill test certificates and inspection certificates signed and issued with the consignment.",
              },
              {
                title: "Statutory filings",
                body: "Documents requiring a DSC, signed from the system that produced them.",
              },
              {
                title: "Contracts and approvals",
                body: "Individual signatures where a named person's authority is what matters.",
              },
            ],
          ],
        },
      ],
    },
    faqSection("bg", "Questions", [
      [
        "Which certifying authorities are supported?",
        "DSCs from government-approved CAs, both Class 3 organisation certificates and individual certificates. Your existing certificates are usable.",
      ],
      [
        "Is a digital signature legally valid in India?",
        "Digital signatures using a DSC from a licensed CA have statutory recognition under the Information Technology Act. Whether that satisfies a specific requirement depends on the document and the regulator, and that is a question for your legal counsel.",
      ],
      [
        "How does mass signing handle a failure part-way?",
        "Each document is signed and committed individually with its status recorded, so a failure at document 340 of 500 leaves 339 validly signed and clearly identifies the rest.",
      ],
      [
        "Does the signature survive if the document is edited?",
        "No, and that is the point. Any alteration after signing invalidates the signature, which is what makes it evidence.",
      ],
    ]),
  ],
};

/** SCR-014, products-production-process.jsx. */
const PRODUCTION_PROCESS: DetailPageContent = {
  eyebrow: EYEBROW,
  title: "TAMS Production Process",
  breadcrumbLabel: "TAMS Production Process",
  intro:
    "Pipe-level traceability on SAP S/4HANA Public Cloud. From bloom to bundled pipe, every individual piece is identified, measured and accounted for.",
  sections: [
    {
      id: "problem",
      tone: "bg",
      heading: { eyebrow: "Problem", title: "The problem" },
      blocks: [
        {
          kind: "lead",
          size: "xl",
          measure: "1080",
          text: "Public Edition gives you a production order. It does not give you the pipe.",
        },
        {
          kind: "paragraph",
          text: "In metals and steel make-to-order manufacturing, one bloom becomes several billets, each billet becomes a shell, each shell becomes a finished pipe. Standard SAP tracks quantity at each stage. It does not tell you which pipe came from which heat, what it weighed at each operation, or where the process loss went. The usual workaround is a parallel spreadsheet — which means the traceability your customer asks for exists outside the system that ships the goods.",
        },
      ],
    },
    {
      id: "overview",
      tone: "sunk",
      heading: { eyebrow: "Overview", title: "What it is" },
      blocks: [
        {
          kind: "lead",
          size: "lg",
          measure: "1080",
          text: "Four custom Fiori applications on SAP S/4HANA Cloud, Public Edition, covering the full make-to-order flow.",
        },
        {
          kind: "attributeTable",
          caption: "TAMS Production Process at a glance",
          columns: ["Attribute", "Description"],
          labelWidth: "md",
          rows: [
            { label: "Industry", value: "Metal and steel" },
            { label: "Manufacturing type", value: "Make-to-Order (MTO)" },
            { label: "Platform", value: "SAP S/4HANA Cloud, Public Edition" },
            {
              label: "Production stages",
              value: "Raw material, semi-finished goods, finished goods",
            },
            { label: "Raw material", value: "Bloom" },
            { label: "Semi-finished goods", value: "Billet, shell" },
            { label: "Finished goods", value: "Pipe" },
            { label: "Demand source", value: "Sales order" },
            { label: "Planning method", value: "MRP" },
            { label: "Traceability level", value: "Individual pipe" },
          ],
        },
      ],
    },
    {
      id: "flow",
      tone: "bg",
      heading: { eyebrow: "Flow", title: "End-to-end process flow" },
      blocks: [
        {
          kind: "stepGrid",
          steps: [
            { title: "Sales order", detail: "Standard — demand creation" },
            { title: "MRP run", detail: "Standard — material requirements planning" },
            { title: "Planned orders", detail: "Standard — created for all stages" },
            { title: "Production orders", detail: "Standard — simultaneous conversion" },
            {
              title: "Billet production order",
              detail: "Custom — mother billet to child billets",
              dashed: true,
            },
            {
              title: "Shell production order",
              detail: "Custom — child billet to shell",
              dashed: true,
            },
            {
              title: "Pipe production order",
              detail: "Custom — shell to finished pipe",
              dashed: true,
            },
            {
              title: "Serial number assignment",
              detail: "Custom — unique number per pipe",
              dashed: true,
            },
            {
              title: "Pipe-level traceability",
              detail: "Custom — across all stages",
              dashed: true,
            },
          ],
          legend: { solid: "Standard SAP", dashed: "Custom applications" },
        },
        {
          kind: "caption",
          text: "Steps 1 to 4 are standard SAP. Steps 5 to 9 are the custom applications.",
        },
      ],
    },
    {
      id: "applications",
      tone: "sunk",
      heading: { eyebrow: "Applications", title: "The four applications" },
      blocks: [
        {
          kind: "operations",
          rows: [
            { title: "Billet production order", meta: "1 operation", chips: ["Cutting"] },
            {
              title: "Semi-finished pipe (SFG)",
              meta: "6 operations",
              chips: [
                "Rotary hearth furnace",
                "Piercer",
                "Fine quality mill",
                "Extraction mill",
                "Walk beam furnace",
                "Sizing",
              ],
            },
            {
              title: "Finished goods (FG) pipes",
              meta: "11 operations",
              chips: [
                "Batch saw cutting",
                "Straightening",
                "Visual dimensional inspection",
                "Non-destructive testing",
                "Ultrasonic testing",
                "Face end bevel",
                "Hydro pressure testing",
                "Varnish",
                "Stenciling",
                "Final inspection",
                "Bundling",
              ],
            },
          ],
        },
        {
          kind: "caption",
          text: "Three production orders, eighteen operations. The billet serial number is retained across every SFG operation, and each SFG shell serial maps one-to-one to an FG pipe serial — which is what makes bloom-to-pipe genealogy unbroken.",
        },
        {
          kind: "numberedDetails",
          items: [
            {
              title: "Cut Plan",
              paragraphs: [
                "Defines how a bloom is divided into multiple billets, before anything is cut. The planner selects the billet source — mother billet procured from the vendor, excess child billet left from a previous cycle, or hold billet retained after an unplanned stoppage — then enters supplier batch, heat number, material batch, bloom length, billet length and quantity. The number of cut billets is calculated from the defined length.",
                "On save, selected material batches, components and component quantities transfer automatically into the standard SAP billet production order. No re-entry.",
              ],
            },
            {
              title: "Child Billet",
              paragraphs: [
                "Executes and confirms billet production from the cut plan. Each billet receives a unique serial number, generated as a production order and serial number combination. Bloom weight, total billet weight, cut billet weight, input and cut lengths and process loss during cutting are captured. Processing status is recorded as excess, drop, scrap or hold.",
              ],
            },
            {
              title: "Semi-Finished Pipe (SFG)",
              paragraphs: [
                "Converts billets into shells across six operations. Process loss is captured at the rotary hearth furnace, fine quality mill and walk beam furnace. Input and output length and weight are recorded at each applicable operation, along with shell drop quantity and weight. The billet serial number is retained across all six operations, so genealogy is unbroken.",
              ],
            },
            {
              title: "Finished Goods (FG) Pipes",
              paragraphs: [
                "Manufactures, inspects and prepares pipes for dispatch across eleven operations. FG pipe serial numbers are generated automatically at batch saw cutting, with a one-to-one link between each SFG shell serial and each FG pipe serial. Front and tail scrap, bevel angle, hydro test results, VDI pipe number and bundle number are captured at the operations that produce them. Each pipe carries a status of accept, reject, rework or work in progress.",
              ],
            },
          ],
        },
      ],
    },
    {
      id: "integration",
      tone: "inverse",
      heading: { eyebrow: "Integration", title: "It updates standard SAP, not a parallel system" },
      blocks: [
        {
          kind: "attributeTable",
          caption: "What each custom application updates in standard SAP",
          columns: ["Custom application", "What it updates in standard SAP"],
          labelWidth: "lg",
          rows: [
            {
              label: "Cut Plan",
              value:
                "Material batch, components and component quantities in the billet production order",
            },
            {
              label: "Billet, SFG and FG",
              value:
                "Production order release, goods issue quantity, confirmation quantity and goods receipt quantity",
            },
            {
              label: "All applications",
              value: "Production order system status — REL, PCNF, DLV — updated automatically",
            },
          ],
        },
        {
          kind: "paragraph",
          text: "No duplicate data maintenance. The custom applications are where the shop floor works; standard SAP stays the system of record.",
        },
      ],
    },
    faqSection("bg", "Questions", [
      [
        "Is this only for pipes?",
        "The applications were built for seamless pipe manufacturing, where bloom-to-pipe genealogy is the requirement. The pattern — a parent material cut into serialised children, tracked through staged operations — applies to other metals and steel make-to-order processes. Scope for a different product would be confirmed in a fit-gap assessment.",
      ],
      [
        "Does this work on Private Edition?",
        "The process design transfers. The specific value here is that it works on Public Edition, where extensibility is constrained and this level of traceability is otherwise hard to achieve.",
      ],
      [
        "Will it survive quarterly upgrades?",
        "It is built as Fiori applications integrating with standard production orders through released interfaces, not as modifications to standard objects.",
      ],
      [
        "Can operations be skipped?",
        "Yes. Operations 2 to 10 in the FG flow can be skipped where the product does not require them, with the skip recorded.",
      ],
    ]),
  ],
};

/** SCR-015, products-vendor-portal.jsx. */
const VENDOR_PORTAL: DetailPageContent = {
  eyebrow: EYEBROW,
  title: "TAMS Vendor Portal",
  breadcrumbLabel: "TAMS Vendor Portal",
  intro:
    "Your suppliers see live SAP data — RFQs, purchase orders, shipment notices, invoice and payment status — without a copy of it existing anywhere else.",
  sections: [
    {
      id: "principle",
      tone: "sunk",
      heading: { eyebrow: "Principle", title: "The principle it is built on" },
      blocks: [
        {
          kind: "lead",
          size: "lg",
          measure: "1080",
          text: "If S/4HANA can produce a value, the portal reads it live and never stores a copy. That one rule answers the objection every IT team raises first — no duplicated master data, no reconciliation between portal and ERP, no stale payment status, and nothing to re-sync after a change in SAP.",
        },
        {
          kind: "bulletColumns",
          columns: [
            {
              label: "What the supplier sees",
              items: [
                "RFQs and quotation requests",
                "Purchase orders to acknowledge",
                "Shipment notices they raise",
                "Invoice and payment status",
                "Delivery and quality performance",
              ],
            },
            {
              label: "How it is served",
              items: [
                "Read live from S/4HANA through released APIs",
                "No replicated master data",
                "No parallel database to secure or back up",
                "No reconciliation between portal and ERP",
                "Auditable access — who saw what, and when",
              ],
            },
          ],
        },
        {
          kind: "caption",
          text: "Two audiences, one diagram. The left column is the purchasing conversation; the right column is the IT conversation. They are usually different meetings.",
        },
      ],
    },
    {
      id: "capability",
      tone: "bg",
      heading: { eyebrow: "Capability", title: "For your purchasing team" },
      blocks: [
        {
          kind: "cards",
          titleSize: "lg",
          rows: [
            [
              {
                title: "RFQ and quotation",
                body: "Issue enquiries, collect structured quotations, compare on like terms.",
              },
              {
                title: "Purchase order acknowledgement",
                body: "Confirmation with date and quantity, exceptions visible immediately rather than at delivery.",
              },
              {
                title: "Shipment notices",
                body: "Advance notice ahead of arrival, feeding the gate so security knows what is coming.",
              },
            ],
            [
              {
                title: "Invoice and payment status",
                body: "Suppliers self-serve the question that generates most of your inbound calls.",
              },
              {
                title: "Supplier onboarding",
                body: "Structured registration and document collection, with approval routing.",
              },
              {
                title: "Performance visibility",
                body: "On-time delivery and quality against schedule, shared with the supplier.",
              },
            ],
          ],
        },
      ],
    },
    {
      id: "positioning",
      tone: "inverse",
      heading: { eyebrow: "Positioning", title: "Why this instead of a full source-to-pay suite" },
      blocks: [
        {
          kind: "lead",
          size: "md",
          measure: "1080",
          text: "SAP Ariba is the right answer for large procurement organisations that need full source-to-pay, supplier risk and network reach, and we implement it. The Vendor Portal exists for the mid-market manufacturer whose actual problem is narrower: suppliers phoning to ask where their payment is, and purchase orders acknowledged by email.",
        },
      ],
    },
    faqSection("bg", "Questions", [
      [
        "When will it be available?",
        "It is in development against SAP fixture data. We are talking to early-access customers now.",
      ],
      [
        "Can we see a demo?",
        "Yes, and we usually run two — one for the purchasing team focused on the workflow, one for IT focused on integration and data handling. They are different conversations and combining them serves neither.",
      ],
      [
        "How many suppliers can it handle?",
        "It is designed for the supplier base of a mid-market manufacturer, and scales with your SAP APIs rather than independently of them.",
      ],
    ]),
  ],
};

/** SCR-016, products-connected-factory.jsx. */
const CONNECTED_FACTORY: DetailPageContent = {
  eyebrow: EYEBROW,
  title: "TAMS Connected Factory",
  breadcrumbLabel: "TAMS Connected Factory",
  intro: "Connected factory with measurable production outcomes.",
  sections: [
    {
      id: "outcome",
      tone: "bg",
      compact: true,
      blocks: [
        {
          kind: "stat",
          value: "85%",
          text: "reduction in unplanned downtime. An automotive manufacturer. Machine data retrieved from the shop floor, turned into a dashboard that plant leadership uses to make decisions, and reported into SAP against the production order.",
        },
      ],
    },
    {
      id: "problem",
      tone: "sunk",
      heading: { eyebrow: "Problem", title: "The problem" },
      blocks: [
        {
          kind: "lead",
          size: "xl",
          measure: "1080",
          text: "Your machines already produce data. Most of it stops at the machine.",
        },
        {
          kind: "paragraph",
          text: "The plant knows its real downtime. SAP knows the planned order. Between them sits a whiteboard, a shift register, or a spreadsheet somebody updates at the end of the day. By the time the two numbers meet, the shift is over and nobody can say which one is right.",
        },
      ],
    },
    {
      id: "architecture",
      tone: "bg",
      heading: { eyebrow: "Architecture", title: "How it works" },
      blocks: [
        {
          kind: "rail",
          steps: [
            { title: "Machine" },
            { title: "Sensors" },
            { title: "IIoT platform" },
            { title: "Machine and process data" },
            { title: "TAMS Industry Intelligence" },
            { title: "SAP" },
          ],
        },
        {
          kind: "caption",
          text: "Six stages from the machine to the ERP. The IIoT platform is selected to fit the equipment and environment — TAMS is not tied to a single vendor, and no vendor is named on the site.",
        },
        {
          kind: "paragraph",
          text: "Sensors on the machine feed an IIoT platform. Machine and process data passes through TAMS Industry Intelligence, which turns raw signal into the measures your plant actually manages by. Those measures land in SAP, against the order, the work centre and the material.",
        },
      ],
    },
    {
      id: "layer",
      tone: "inverse",
      heading: { eyebrow: "The layer", title: "TAMS Industry Intelligence" },
      blocks: [
        {
          kind: "lead",
          size: "md",
          measure: "1080",
          text: "TAMS Industry Intelligence sits between the shop floor and SAP. It takes raw machine signal — states, counts, cycle times, sensor readings — and turns it into the measures a plant manages by: OEE, downtime by reason, utilization, energy per unit.",
        },
        {
          kind: "paragraph",
          text: "It then writes those measures into SAP against the order, the work centre and the material, so shop-floor reality and ERP reporting agree instead of being reconciled.",
        },
        {
          kind: "callout",
          title: "It reads from the machine layer. It never writes to it.",
          text: "Your production equipment is not controlled, altered or interrupted by anything in this stack.",
        },
      ],
    },
    {
      id: "measures",
      tone: "bg",
      heading: { eyebrow: "Measures", title: "What you get" },
      blocks: [
        {
          kind: "cards",
          titleSize: "lg",
          rows: [
            [
              {
                title: "OEE",
                body: "Availability, performance and quality, calculated from machine state rather than from a shift report.",
              },
              {
                title: "Downtime",
                body: "Captured as it happens, attributed by reason, and visible by machine, line and shift.",
              },
              {
                title: "Machine utilization",
                body: "Actual running time against available time, per asset.",
              },
            ],
            [
              {
                title: "Energy",
                body: "Consumption measured against output, so you see energy per unit rather than energy per month.",
              },
              {
                title: "Predictive maintenance",
                body: "Condition trends that show a machine drifting before it stops.",
              },
              {
                title: "Production analytics",
                body: "Output, cycle time and yield in SAP, against the order that produced them.",
              },
            ],
          ],
        },
      ],
    },
    {
      id: "adoption",
      tone: "sunk",
      heading: { eyebrow: "Adoption", title: "The dashboard is the point" },
      blocks: [
        {
          kind: "lead",
          size: "md",
          measure: "1080",
          text: "Data in SAP is where the numbers become official. The dashboard is where somebody acts on them. Plant leadership sees downtime as it accumulates, attributed by reason, by machine and by shift — early enough in the shift to do something about it, not the next morning in a report.",
        },
      ],
    },
    {
      id: "positioning",
      tone: "bg",
      heading: { eyebrow: "Positioning", title: "Why it matters that this lands in SAP" },
      blocks: [
        {
          kind: "lead",
          size: "md",
          measure: "1080",
          text: "Plenty of platforms will show you a shop-floor dashboard. The difference is where the numbers end up. When OEE and downtime sit in a separate system they become a second version of the truth that operations trusts and finance does not. When they land in SAP against the production order, costing, planning and maintenance all use the same figures.",
        },
      ],
    },
    {
      id: "next",
      tone: "inverse",
      heading: { eyebrow: "Next", title: "Where it leads" },
      blocks: [
        {
          kind: "lead",
          size: "md",
          measure: "1080",
          text: "Connected Factory is the data layer. Once the measures are reliable and in SAP, TAMS Digital Manufacturing & AI is what runs on top of them. Most customers buy in that order, because prediction is only as good as the data underneath it.",
        },
        {
          kind: "link",
          label: "TAMS Digital Manufacturing & AI",
          href: productHref("digital-manufacturing-ai"),
        },
      ],
    },
    faqSection("bg", "Questions", [
      [
        "Do we need to replace our machines?",
        "No. Sensors are fitted to what you have. Older machines with no digital output need a sensor; newer machines often expose data already.",
      ],
      [
        "Will this interfere with production?",
        "No. The stack reads from the machine layer and never writes to it. Nothing here can change how a machine runs.",
      ],
      [
        "What if we already have a shop-floor system?",
        "Then the question is whether its numbers reach SAP. If they do, you may not need this. If they sit in a separate dashboard, this is the missing link rather than a replacement.",
      ],
      [
        "How long does it take?",
        "It depends on machine count and how much equipment already exposes data. A single line is a matter of weeks; a whole plant is a project.",
      ],
      [
        "Which IIoT platform do you use?",
        "We select the platform to fit your equipment and environment. We are not tied to one vendor, and we will explain the choice we recommend for your plant.",
      ],
    ]),
  ],
};

/** SCR-017, products-digital-manufacturing-ai.jsx. */
const DIGITAL_MANUFACTURING_AI: DetailPageContent = {
  eyebrow: EYEBROW,
  title: "TAMS Digital Manufacturing & AI",
  breadcrumbLabel: "TAMS Digital Manufacturing & AI",
  intro: "Connecting SAP, the shop floor and AI to improve manufacturing performance.",
  sections: [
    {
      id: "overview",
      tone: "bg",
      heading: {
        eyebrow: "Overview",
        title: "AI in manufacturing usually arrives as a pilot that never leaves the pilot.",
      },
      blocks: [
        {
          kind: "lead",
          size: "lg",
          measure: "1080",
          text: "We package it as six solutions, each built around one outcome you can measure before and after.",
        },
        {
          kind: "cards",
          titleSize: "md",
          accentTop: true,
          rows: [
            [
              {
                title: "TAMS AI Process Automation",
                body: "Automate repetitive business processes",
              },
              { title: "TAMS Predictive Maintenance", body: "Reduce unplanned downtime" },
              { title: "TAMS AI Quality Inspection", body: "Reduce defects and inspection effort" },
            ],
            [
              {
                title: "TAMS Manufacturing Intelligence",
                body: "Improve production visibility and decision-making",
              },
              { title: "TAMS Energy Intelligence", body: "Reduce energy consumption per unit" },
              { title: "TAMS Supplier Intelligence", body: "Predict supplier delays and risks" },
            ],
          ],
        },
        {
          kind: "caption",
          text: "Six packages, each tied to one measurable outcome. Only the first is running in production today, and the page says so.",
        },
        {
          kind: "callout",
          text: "Process automation is running in production today. The five below are built on the same SAP and shop-floor foundation, and we scope each against your data before committing to an outcome.",
        },
      ],
    },
    {
      id: "delivered",
      tone: "sunk",
      heading: { eyebrow: "Delivered", title: "TAMS AI Process Automation — delivered" },
      blocks: [
        {
          kind: "rail",
          steps: [
            { title: "Invoice PDF" },
            { title: "OCR" },
            { title: "Data extraction" },
            { title: "SAP" },
          ],
        },
        {
          kind: "caption",
          text: "Delivered and running. Supplier invoices arrive as PDFs, the document is read, fields are extracted and posted into SAP for matching. Only exceptions reach a person.",
        },
        {
          kind: "paragraph",
          text: "Supplier invoices arrive as PDFs. The document is read, the fields extracted — vendor, invoice number, date, line items, quantities, values, tax — and posted into SAP for matching. Only exceptions reach a person.",
        },
        {
          kind: "paragraph",
          text: "If suppliers submit invoices through TAMS Vendor Portal, the extraction step gets cleaner input and fewer exceptions.",
        },
        { kind: "link", label: "TAMS Vendor Portal", href: productHref("vendor-portal") },
      ],
    },
    {
      id: "scoped",
      tone: "inverse",
      heading: { eyebrow: "Scoped", title: "The other five" },
      blocks: [
        {
          kind: "cards",
          titleSize: "md",
          rows: [
            [
              {
                title: "TAMS Predictive Maintenance",
                body: "Machine condition data trended against failure history to flag an asset drifting out of normal. The alert becomes a maintenance notification in SAP against the equipment.",
                note: "Needs Connected Factory as the data layer.",
              },
              {
                title: "TAMS AI Quality Inspection",
                body: "Cameras inspect for surface defects, dimensional variance and assembly errors at line speed. Results post to the SAP inspection lot.",
                note: "Needs cameras, lighting and a labelled image set — a project, not a switch.",
              },
              {
                title: "TAMS Manufacturing Intelligence",
                body: "Shop-floor data and SAP order data in one view: output against plan, cycle time, yield, downtime by reason.",
                note: "Needs Connected Factory.",
              },
            ],
            [
              {
                title: "TAMS Energy Intelligence",
                body: "Energy metered at machine and line level, divided by actual output. Shows which assets, shifts and product mixes cost most to run.",
                note: "Needs asset-level meters.",
              },
              {
                title: "TAMS Supplier Intelligence",
                body: "Supplier delivery history and quality performance in SAP scored to flag which open orders are likely to arrive late.",
                note: "Needs enough purchase history for the pattern to be real.",
              },
            ],
          ],
        },
      ],
    },
    faqSection("bg", "Questions", [
      [
        "Which of these have you actually delivered?",
        "AI Process Automation, in the invoice PDF to OCR to data extraction flow. The other five are scoped against your data before we commit to an outcome. We would rather tell you that here than in month three.",
      ],
      [
        "Do we need Connected Factory first?",
        "For predictive maintenance and manufacturing intelligence, yes in practice — prediction is only as good as the data underneath it. Process automation and supplier intelligence work from data already in SAP.",
      ],
      [
        "Is this SAP Business AI or something else?",
        "Both, depending on the package. Where SAP already has an embedded capability we activate it rather than rebuild it. Where it does not, we build.",
      ],
    ]),
  ],
};

export const PRODUCTS_FAMILY: DetailFamily = {
  label: "Products",
  routes: PRODUCT_ROUTES,
  pages: {
    "gate-entry": GATE_ENTRY,
    exim: EXIM,
    digisign: DIGISIGN,
    "production-process": PRODUCTION_PROCESS,
    "vendor-portal": VENDOR_PORTAL,
    "connected-factory": CONNECTED_FACTORY,
    "digital-manufacturing-ai": DIGITAL_MANUFACTURING_AI,
  },
};
